raw_data: "data/raw/raw_reactions.csv"
filtered_data: "data/processed/filtered_reactions.csv"
astatine_data: "data/processed/astatine_reactions.csv"
mapped_data: "data/processed/atom_mapped_reactions.csv"
evodex_p: "data/processed/EVODEX-P_partial_reactions.csv"
evodex_r: "data/processed/EVODEX-R_full_reactions.csv"
evodex_e: "data/processed/EVODEX-E_reaction_operators.csv"
evodex_c: "data/processed/EVODEX-C_reaction_operators.csv"
evodex_n: "data/processed/EVODEX-N_reaction_operators.csv"
evodex_em: "data/processed/EVODEX-Em_reaction_operators.csv"
evodex_cm: "data/processed/EVODEX-Cm_reaction_operators.csv"
evodex_nm: "data/processed/EVODEX-Nm_reaction_operators.csv"
evodex_m: "data/processed/EVODEX-M_unique_masses.csv"
evodex_f: "data/processed/EVODEX-F_unique_formulas.csv"
template_dir: "pipeline/analysis_and_website/templates"
static_dir: "pipeline/analysis_and_website/static"
