#!/usr/bin/env python3
"""
Build a PDF summarizing mechanistic consistency across the top 5 enzymes.

Inputs (generated by prior scripts)
- analysis/top5_diverse_enzymes_operators/output/top5_enzyme_operators.csv
- analysis/top5_diverse_enzymes_operators/output/operators_svg/Bm/enzyme{N}_Bm{k}.svg
- analysis/top5_diverse_enzymes_operators/output/operators_svg/Cm/enzyme{N}_Cm{k}.svg
- analysis/top5_diverse_enzymes_operators/output/operators_svg/Em/enzyme{N}_Em{k}.svg

Output
- analysis/top5_diverse_enzymes_operators/output/MechanisticConsistency_Top5Enzymes.pdf
"""

from __future__ import annotations

import os
from typing import Dict, List

import pandas as pd

from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak
from reportlab.graphics import renderPDF
from reportlab.platypus.flowables import Flowable

from svglib.svglib import svg2rlg


OUTPUT_DIR = "analysis/top5_diverse_enzymes_operators/output"
SVG_ROOT = os.path.join(OUTPUT_DIR, "operators_svg")

OPS_CSV = os.path.join(OUTPUT_DIR, "top5_enzyme_operators.csv")
OUT_PDF = os.path.join(OUTPUT_DIR, "MechanisticConsistency_Top5Enzymes.pdf")

LEVELS = ["Em", "Cm", "Bm"]  # display order


class SVGFlowable(Flowable):
    def __init__(self, svg_path: str, target_width_pts: float):
        super().__init__()
        self.svg_path = svg_path
        self.target_width_pts = target_width_pts
        self._drawing = None
        self.width = target_width_pts
        self.height = 0

        drawing = svg2rlg(svg_path)
        if drawing is None:
            raise ValueError(f"Could not read SVG: {svg_path}")

        sx = target_width_pts / float(drawing.width) if drawing.width else 1.0
        sy = sx
        drawing.scale(sx, sy)

        self._drawing = drawing
        self.height = float(drawing.height) * sy if drawing.height else 0

    def draw(self):
        renderPDF.draw(self._drawing, self.canv, 0, 0)


def _ensure_inputs_exist() -> None:
    if not os.path.exists(OPS_CSV):
        raise FileNotFoundError(f"Missing operators CSV: {OPS_CSV}")

    for lvl in ["Bm", "Cm", "Em"]:
        p = os.path.join(SVG_ROOT, lvl)
        if not os.path.isdir(p):
            raise FileNotFoundError(
                f"Missing SVG folder for {lvl}: {p}\n"
                "Run the SVG rendering script first."
            )


def _stable_enzyme_order(df: pd.DataFrame) -> List[str]:
    tmp = (
        df[["enzyme_id", "organism", "ec_num", "protein_refs"]]
        .drop_duplicates()
        .sort_values(["ec_num", "organism", "protein_refs", "enzyme_id"])
    )
    return tmp["enzyme_id"].tolist()[:5]


def _counts_and_order_for_level(df_enzyme: pd.DataFrame, level: str) -> pd.DataFrame:
    """
    Return a table with columns:
      operator_hash, n
    sorted by n desc then hash asc.
    """
    hcol = f"{level}_hash"
    out = (
        df_enzyme[df_enzyme[hcol].astype(str).str.len() > 0]
        .groupby(hcol)
        .size()
        .reset_index(name="n")
        .rename(columns={hcol: "operator_hash"})
        .sort_values(["n", "operator_hash"], ascending=[False, True])
        .reset_index(drop=True)
    )
    return out


def _svg_path(enzyme_num: int, level: str, idx: int) -> str:
    # Matches the naming used by the render script:
    # enzyme{N}_{LEVEL}{k}.svg
    return os.path.join(SVG_ROOT, level, f"enzyme{enzyme_num}_{level}{idx}.svg")


def main() -> None:
    _ensure_inputs_exist()

    df = pd.read_csv(OPS_CSV)
    df["enzyme_id"] = (
        df["organism"].astype(str)
        + "_"
        + df["protein_refs"].astype(str)
        + "_"
        + df["ec_num"].astype(str)
    )

    enzyme_ids = _stable_enzyme_order(df)
    enzyme_num_map: Dict[str, int] = {eid: i + 1 for i, eid in enumerate(enzyme_ids)}

    styles = getSampleStyleSheet()
    title_style = styles["Title"]
    h_style = ParagraphStyle(
        "enzyme_header",
        parent=styles["Heading2"],
        spaceBefore=10,
        spaceAfter=4,
    )
    sub_style = ParagraphStyle(
        "enzyme_subheader",
        parent=styles["Normal"],
        spaceBefore=0,
        spaceAfter=8,
    )
    lvl_style = ParagraphStyle(
        "level_header",
        parent=styles["Heading3"],
        spaceBefore=8,
        spaceAfter=2,
    )
    small_style = ParagraphStyle(
        "small",
        parent=styles["Normal"],
        fontSize=10,
        leading=12,
        spaceBefore=0,
        spaceAfter=4,
    )

    doc = SimpleDocTemplate(
        OUT_PDF,
        pagesize=letter,
        leftMargin=0.85 * inch,
        rightMargin=0.85 * inch,
        topMargin=0.85 * inch,
        bottomMargin=0.85 * inch,
        title="Mechanistic Consistency Across Five Mechanistically Diverse Enzymes",
    )

    story = []

    story.append(
        Paragraph(
            "Mechanistic Consistency Across Five Mechanistically Diverse Enzymes",
            title_style,
        )
    )
    story.append(Spacer(1, 0.25 * inch))
    story.append(
        Paragraph(
            "This file summarizes reaction-level mechanistic variation within five enzymes, each defined by a unique combination "
            "of organism, UniProt accession number, and EC classification. The enzymes were selected as those with the highest number "
            "of reactions, limited to entries with accession numbers and uniqueness at EC level 3. For each system, EVODEX-derived "
            "Bm, Cm, and Em operators were computed and aggregated across all associated reactions.",
            styles["Normal"],
        )
    )
    story.append(PageBreak())

    target_svg_width = 6.7 * inch

    for eid in enzyme_ids:
        enzyme_num = enzyme_num_map[eid]
        df_e = df[df["enzyme_id"] == eid].copy()

        organism = str(df_e["organism"].iloc[0])
        ec_num = str(df_e["ec_num"].iloc[0])
        protein_refs = str(df_e["protein_refs"].iloc[0]).strip()
        protein_db = str(df_e["protein_db"].iloc[0]).strip()
        n_reactions = int(df_e.shape[0])

        story.append(Paragraph(f"[{enzyme_num}] {organism} - EC {ec_num}", h_style))

        prot = protein_refs.strip("[]").strip().strip("'").strip('"')
        if prot:
            prot_line = f"Protein: {prot} ({protein_db}) | Reactions: {n_reactions}"
        else:
            prot_line = f"Protein: (missing) | Reactions: {n_reactions}"
        story.append(Paragraph(prot_line, sub_style))

        for level in LEVELS:
            counts = _counts_and_order_for_level(df_e, level)
            n_unique = int(counts.shape[0])

            story.append(Paragraph(f"EVODEX-{level} ({n_unique} unique)", lvl_style))

            for idx in range(1, n_unique + 1):
                n = int(counts["n"].iloc[idx - 1])
                svg_path = _svg_path(enzyme_num, level, idx)

                story.append(Paragraph(f"(n={n})", small_style))

                if os.path.exists(svg_path):
                    try:
                        story.append(SVGFlowable(svg_path, target_svg_width))
                    except Exception as exc:
                        story.append(
                            Paragraph(
                                f"[!] Could not place SVG {os.path.basename(svg_path)}: {exc}",
                                small_style,
                            )
                        )
                else:
                    story.append(Paragraph(f"[!] Missing SVG: {svg_path}", small_style))

                story.append(Spacer(1, 0.10 * inch))

            story.append(Spacer(1, 0.15 * inch))

        story.append(PageBreak())

    doc.build(story)
    print(f"Wrote PDF: {OUT_PDF}")


if __name__ == "__main__":
    main()
